Add forms for post, comment and like.
chudisoft/RubyBlog pull request #7
Opened 2024-01-15 14:18 UTC by chudisoft

[Project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/forms_project_v1_1.md#project-requirements)

    Create a method called current_user in your ApplicationController to make current user data available to all controllers.
        It will return the first user from the database.
        Don't worry about proper authentication at this time. You will add it in the upcoming projects.
    Create forms to perform the following functions:
        Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
        Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
    Allow Users to add likes to Posts.

2024-01-15 15:00 UTC, DammyShittu requested changes
Hi @chudisoft,

## Highlights
✔️ Like and comment creation feature

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-15 15:00 UTC, DammyShittu commented on config/routes.rb
> +  get '/users/:user_id/posts/:id/like', to: 'likes#create', as: 'user_post_like'
- [ ] Kindly use the correct route for the like creation. The like should be wrapped within the posts and users routes, so just like `:user_id`, there should be `:post_id`

- [ ] The like create should be a `post` request not `get` request

  ```
  post `/users/:user_id/posts/:post_id/likes`, ...
  ```

2024-01-15 15:00 UTC, DammyShittu commented on config/routes.rb
> +  post '/users/:user_id/posts/:id/comments/create' , to: 'comments#create', as: 'user_post_comments'
- [ ] The comments routes should use `:post_id`, not `:id`.

- [ ] For the route on line 13, there is no use for `/create`. The post create route should end at the `/comments` word.

  ```
  post '/users/:user_id/posts/:post_id/comments', ...
  ```

2024-01-15 15:00 UTC, DammyShittu commented on config/routes.rb
> +  post '/users/:user_id/posts/:id/comments/create' , to: 'comments#create', as: 'user_post_comments'
- **[OPTIONAL]** All these routes can be defined more conventionally and shortly.

  ```
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  ```

  When you run `rails routes` in the terminal, this is what the routes should look like.

  ![image](https://github.com/chudisoft/RubyBlog/assets/54848363/59957905-617c-4ece-b4b9-7e68d90f4066)

2024-01-15 15:00 UTC, DammyShittu commented on config/routes.rb
> +  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
- [ ] Kindly create the route for post create action

2024-01-15 15:00 UTC, DammyShittu commented on README.md
- [ ] Kindly remove this migration file:

  ```
  db\migrate\20231026234155_add_indeces.rb
  ```

  It prevents your project from being set up and raises duplicate index error. You are defining indexes there but, those indexes already exist before getting to that file. Notice that you have indexes in the migration files already.

2024-01-15 15:00 UTC, DammyShittu commented on app/controllers/posts_controller.rb
> +
- [ ] The post should be created using the `current_user` method you defined in the application controller.

2024-01-15 15:00 UTC, DammyShittu commented on app/views/posts/new.html.erb
> +<%= form_for Post.new do |f| %>
- [ ] There is an error when I visit this page, so I cannot create post from the browser. Kindly fix it.

  ![image](https://github.com/chudisoft/RubyBlog/assets/54848363/54a6141e-7f47-45d9-8e50-ed58b0ec66a3)

2024-01-16 08:32 UTC, skyv26 approved these changes
## Hi @chudisoft, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDJhMjgwMDkxOGE3NjA4MjIzYTVjYmExMTFiNmUxYjgxN2FlN2U5NCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/FEzcI0TlDxkdbaHTwV/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implemented the features ✅ 
- Nice *UI* design ✅ 
![image](https://github.com/chudisoft/RubyBlog/assets/66476329/1cb6c024-5174-4fb8-b2ae-8ea771d4dc03)


## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-25 11:19 UTC, merged